DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS course_enrolled;
DROP TABLE IF EXISTS curriculums CASCADE;
DROP TABLE IF EXISTS curriculum_details;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS course_co_requisites;
DROP TABLE IF EXISTS course_pre_requisites;

DROP TYPE IF EXISTS GROUP_TYPE;
DROP TYPE IF EXISTS MAJOR;